#!/usr/bin/env php
<?php

require_once __DIR__ . '/../vendor/autoload.php';

use SyncZabbixLdapCommand\SyncZabbixLdapCommand;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new SyncZabbixLdapCommand());
$app->run();





